services:
    # Указываем, что все сервисы, находящиеся в папке src/Controller, автоматически становятся доступными
    # Это исключает папки Entity и Repository из автозагрузки сервисов.
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Repository,Kernel.php}'

    # Определение репозитория UserRepository как публичного сервиса
    App\Repository\UserRepository:
        public: true

    # Настройка сервисов для логики аутентификации и авторизации можно добавить здесь
    # В этом примере мы не добавляем дополнительных настроек, но можно определить, например,
    # пользовательский сервис аутентификации, который будет расширять функциональность по мере необходимости.
